-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.boarders
(
    id integer NOT NULL,
    name text COLLATE pg_catalog."default",
    CONSTRAINT boarders_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.boarders
    OWNER to postgres;

GRANT ALL ON TABLE public.boarders TO anon;

GRANT ALL ON TABLE public.boarders TO authenticated;

GRANT ALL ON TABLE public.boarders TO postgres;

GRANT ALL ON TABLE public.boarders TO service_role;
